---
- hosts: all
  become: yes
  become_method: sudo  
  tasks:
          - name: Install python-apt/apache2
            ansible.builtin.package:
                     name:
                             - python3-apt
                             - apache2
                     state: present

          - name: Copy apache.conf
            ansible.builtin.copy:
                     src: files/config/apache.conf
                     dest: /etc/apache2/apache2.conf
                     owner: root
                     group: root
                     mode: '0644'
          - name: Copy index.html
            ansible.builtin.copy:
                     src: files/site/index.html
                     dest: /var/www/html/index.html
                     owner: root
                     group: root
                     mode: '0644'
          - name: Create symbolic link
            ansible.builtin.file:
                     src: /etc/apache2/mods-available/headers.load
                     dest: /etc/apache2/mods-enabled/headers.load
                     state: link
          - name: Restart apache2
            ansible.builtin.service:
                     name: apache2
                     state: restarted