devops:
        hosts:
                demo:
                        ansible_host: 10.128.0.4
                        ansible_user: collin_chappell
                        ansible_ssh_private_key_file: /.ssh/gcpgithub